🔄 INTEGRATE bash library

diff --git a/lib/header b/lib/header
--- a/lib/header
+++ b/lib/header
@@ -6,7 +6,7 @@
 # Fail script if any command fails.
 set -euo pipefail
 
-# Extended globbing is required for pattern matching in arguments with multiple
+# Extended globbing is required for pattern matching in parameters with multiple
 # patterns.
 shopt -s extglob
 
@@ -25,13 +25,11 @@ ${ARGUMENTS}"
   printf \
 'Usage: %s {{options}} %s
 Options:
-  [-c|--config $config_yaml]   Reads from a YAML configuration and converts all
-                               key-value pairs with literal values to
-                               environment variables.
-  [-d|--debug]                 Enables debug mode, showing every executed
-                               statement.
-  [-h|--help]                  Prints usage (this text).%s' \
-    "$(basename "${0}")" "${arguments}" "${ARGUMENTS}"
+  [-c|--config $config_yaml]                                   Read from a YAML configuration and convert all
+                                                               key-value pairs to environment variables.
+  [-d|--debug]                                                 Enable debug mode, showing every executed command.
+  [-h|--help]                                                  Print usage (this text).%s%s' \
+    "$(basename "${0}")" "${arguments}" "${ARGUMENTS}" "${_add_to_usage-}"
 }
 
 SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
@@ -42,45 +40,49 @@ else
 fi
 
 # Colors
-RESET='\e[1m\e[0m'
-BLACK='\e[1m\e[30m'
-RED='\e[1m\e[31m'
-GREEN='\e[1m\e[32m'
-YELLOW='\e[1m\e[33m'
-BLUE='\e[1m\e[34m'
-PURPLE='\e[1m\e[35m'
-CYAN='\e[1m\e[36m'
-WHITE='\e[1m\e[37m'
+if test -t 1; then
+  RESET='\033[0m'
+  BLACK='\033[30m'
+  RED='\033[31m'
+  GREEN='\033[32m'
+  YELLOW='\033[33m'
+  BLUE='\033[34m'
+  PURPLE='\033[35m'
+  CYAN='\033[36m'
+  WHITE='\033[37m'
+else
+  RESET=
+  BLACK=
+  RED=
+  GREEN=
+  YELLOW=
+  BLUE=
+  PURPLE=
+  CYAN=
+  WHITE=
+fi
 
 # Parse arguments.
 # Source guard
 test -n "${_LIB_HEADER_SOURCED+x}" && return 0
 export _LIB_HEADER_SOURCED=true
 
-# Source YAML files.
-for i in ${_yaml_files[@]}; do
-  . "${LIB_PATH}/yaml-to-env" "${i}"
-done
-unset _yaml_files
-
 # Print -d and -h if they were given as arguments. Use this when running another
 # script inside your script to which you want to pass the same arguments that
-# were given to the parent script: ./script $(additional)
-function additional() {
+# were given to the parent script: ./script $(additional-options)
+function additional-options() {
+  printf '%s' "${_ADDITIONAL_OPTIONS-}"
+}
+
+# Print any given arguments other than default options. Use this when running
+# another script inside your script to which you want to pass the same arguments
+# that were given to the parent script: ./script $(additional-options)
+function additional-arguments() {
   printf '%s' "${_ADDITIONAL_ARGUMENTS-}"
 }
 
 # Define an argument.
 function argument() {
-  test -z "${_simple_argument_variables+x}" && export _simple_argument_variables=''
-  test -z "${_simple_argument_parameters+x}" && export _simple_argument_parameters=''
-  test -z "${_simple_argument_descriptions+x}" && export _simple_argument_descriptions=''
-  test -z "${_valued_argument_variables+x}" && export _valued_argument_variables=''
-  test -z "${_valued_argument_parameters+x}" && export _valued_argument_parameters=''
-  test -z "${_valued_argument_descriptions+x}" && export _valued_argument_descriptions=''
-  test -z "${_positional_argument_variables+x}" && export _positional_argument_variables=''
-  test -z "${_positional_argument_descriptions+x}" && export _positional_argument_descriptions=''
-
   local mode=${1}
   local variable=${2}
   local parameter_or_description=${3}
@@ -91,22 +93,22 @@ function argument() {
       printf -v _simple_argument_variables '%s%s\n' "${_simple_argument_variables}" "${variable}"
       printf -v _simple_argument_parameters '%s%s\n' "${_simple_argument_parameters}" "@(${parameter_or_description})"
       printf -v _simple_argument_descriptions '%s%s\n' "${_simple_argument_descriptions}" "${description}"
-      length=$(( ${#description} + 26 - ${#parameter_or_description} )) # 26 = 32 - 5 - 1
+      length=$(( ${#description} + 58 - ${#parameter_or_description} )) # 58 = 64 - 5 - 1
       printf -v ARGUMENTS "%s  [%s] %${length}s\\n" "${ARGUMENTS-}" "${parameter_or_description}" "${description}"
       unset "${variable}"
       ;;
     'valued')
       printf -v _valued_argument_variables '%s%s\n' "${_valued_argument_variables}" "${variable}"
-      printf -v _valued_argument_parameters '%s%s\n' "${_valued_argument_parameters}" "${parameter_or_description}"
+      printf -v _valued_argument_parameters '%s%s\n' "${_valued_argument_parameters}" "@(${parameter_or_description})"
       printf -v _valued_argument_descriptions '%s%s\n' "${_valued_argument_descriptions}" "${description}"
-      length=$(( ${#description} + 25 - ${#parameter_or_description} - ${#variable} )) # 25 = 32 - 6 - 1
-      printf -v ARGUMENTS "%s  [%s %s] %${length}s\\n" "${ARGUMENTS-}" "${parameter_or_description}" "${variable}" "${description}"
+      length=$(( ${#description} + 56 - ${#parameter_or_description} - ${#variable} )) # 59 = 64 - 4 - 1
+      printf -v ARGUMENTS "%s  [%s %s] %${length}s\\n" "${ARGUMENTS-}" "${parameter_or_description}" "\$${variable}" "${description}"
       unset "${variable}"
       ;;
     'positional')
       printf -v _positional_argument_variables '%s%s\n' "${_positional_argument_variables}" "${variable}"
       printf -v _positional_argument_descriptions '%s%s\n' "${_positional_argument_descriptions}" "${parameter_or_description}"
-      length=$(( ${#parameter_or_description} + 26 - ${#variable} )) # 26 = 32 - 5 - 1
+      length=$(( ${#parameter_or_description} + 58 - ${#variable} )) # 58 = 64 - 5 - 1
       printf -v ARGUMENTS "%s  [%s] %${length}s\\n" "${ARGUMENTS-}" "${variable}" "${parameter_or_description}"
       unset "${variable}"
       ;;
@@ -122,6 +124,7 @@ function parse-parameters() {
   local _yaml
 
   # Options
+  test -z "${_ADDITIONAL_OPTIONS+x}" && _ADDITIONAL_OPTIONS=
   test -z "${_ADDITIONAL_ARGUMENTS+x}" && _ADDITIONAL_ARGUMENTS=
   _yaml_files=()
   _i=1
@@ -137,24 +140,24 @@ function parse-parameters() {
         exit 1
       fi
       _yaml=${!_ii}
-      set -- ${*:1:$((_i - 1))} ${*:$((_i + 2))}
+      set -- "${@:1:$((_i - 1))}" "${@:$((_i + 2))}"
       _yaml_files+=("${_yaml}")
       _i=$(( _i - 1))
       ;;
     # [-d|--debug]                 Enables debug mode, showing every executed
     #                              statement.
     '-d'|'--debug')
-      set -x
-      set -- ${*:1:$((_i - 1))} ${*:$((_i + 1))}
+      set -vx
+      set -- "${@:1:$((_i - 1))}" "${@:$((_i + 1))}"
       _i=$(( _i - 1))
-      if ! grep ' \-d' <<<"${_ADDITIONAL_ARGUMENTS}" > /dev/null; then
-        _ADDITIONAL_ARGUMENTS+=' -d'
+      if ! grep ' \-d' <<<"${_ADDITIONAL_OPTIONS}" > /dev/null; then
+        _ADDITIONAL_OPTIONS+=' -d'
       fi
       ;;
     # [-h|--help]                  Prints usage (this text).
     '-h'|'--help')
-      if ! grep ' \-d' <<<"${_ADDITIONAL_ARGUMENTS}" > /dev/null; then
-        _ADDITIONAL_ARGUMENTS+=' -d'
+      if ! grep ' \-h' <<<"${_ADDITIONAL_OPTIONS}" > /dev/null; then
+        _ADDITIONAL_OPTIONS+=' -h'
       fi
       print-usage
       exit 0
@@ -162,6 +165,12 @@ function parse-parameters() {
     esac;
     _i=$(( _i + 1 ))
   done
+
+  # Source YAML files.
+  for i in "${_yaml_files[@]}"; do
+    . "${LIB_PATH}/yaml-to-env" "${i}"
+  done
+  unset _yaml_files
 
   local _positional
   local _variable
@@ -172,15 +181,23 @@ function parse-parameters() {
       case "${1}" in $(printf '%s' "${_simple_argument_parameters}" | head -n "${i}" | tail -n 1))
         _variable=$(printf '%s' "${_simple_argument_variables}" | head -n "${i}" | tail -n 1)
         export ${_variable}=true
+        if ! grep " ${1}" <<<"${_ADDITIONAL_ARGUMENTS}" > /dev/null; then
+          _ADDITIONAL_ARGUMENTS+=" ${1}"
+        fi
         shift
         continue 2
       ;; esac
     done
     for i in $(seq 1 $(printf '%s' "${_valued_argument_variables}" | wc -l)); do
       case "${1}" in $(printf '%s' "${_valued_argument_parameters}" | head -n "${i}" | tail -n 1))
+        _criteria=${1}
         shift
         _variable=$(printf '%s' "${_valued_argument_variables}" | head -n "${i}" | tail -n 1)
-        export ${_variable}=${1}
+        export ${_variable}="${1}"
+        _whole_argument_expression=" ${_criteria} ${1}"
+        if ! grep " ${_whole_argument_expression}" <<<"${_ADDITIONAL_ARGUMENTS}" > /dev/null; then
+          _ADDITIONAL_ARGUMENTS+=" ${_whole_argument_expression}"
+        fi
         shift
         continue 2
       ;; esac
@@ -189,16 +206,35 @@ function parse-parameters() {
       _positional=$(printf '%s' "${_positional_argument_variables}" | head -n "${i}" | tail -n 1)
       if test -z "${!_positional+x}"; then
         export "${_positional}"="${1}"
+        if ! grep " ${1}" <<<"${_ADDITIONAL_ARGUMENTS}" > /dev/null; then
+          _ADDITIONAL_ARGUMENTS+=" ${1}"
+        fi
         shift
         continue 2
       fi
     done
 
-    # Unrecognized argument
-    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2
+    # Allow extra parameters?
+    if ${_ALLOW_EXTRA_PARAMETERS-false}; then
+      break
+    fi
+
+    # Unrecognized parameter
+    printf "${RED}ERROR: Unrecognized parameter '%s'${RESET}\\n" "${1}" 1>&2
     print-usage
     exit 1
   done
+
+  EXTRA_PARAMETERS=( "${@}" )
+}
+
+function allow-extra-parameters() {
+  export _ALLOW_EXTRA_PARAMETERS=true
+}
+
+function add-to-usage() {
+  test -z "${_add_to_usage+x}" && export _add_to_usage=''
+  printf -v _add_to_usage '%s%s\n' "${_add_to_usage}" "${1}"
 }
 
 # Export colors.
@@ -214,8 +250,23 @@ export WHITE
 
 # Export variables and functions.
 export _ADDITIONAL_ARGUMENTS
-export -f additional
+export _ADDITIONAL_OPTIONS
+export -f additional-arguments
+export -f additional-options
+export -f allow-extra-parameters
+export -f argument
+export -f parse-parameters
 export -f print-usage
+
+# Export variables responsible for argument defining & parameter parsing.
+test -z "${_simple_argument_variables+x}" && export _simple_argument_variables=''
+test -z "${_simple_argument_parameters+x}" && export _simple_argument_parameters=''
+test -z "${_simple_argument_descriptions+x}" && export _simple_argument_descriptions=''
+test -z "${_valued_argument_variables+x}" && export _valued_argument_variables=''
+test -z "${_valued_argument_parameters+x}" && export _valued_argument_parameters=''
+test -z "${_valued_argument_descriptions+x}" && export _valued_argument_descriptions=''
+test -z "${_positional_argument_variables+x}" && export _positional_argument_variables=''
+test -z "${_positional_argument_descriptions+x}" && export _positional_argument_descriptions=''
 
 # Export paths.
 export LIB_PATH
diff --git a/lib/spinner b/lib/spinner
--- a/lib/spinner
+++ b/lib/spinner
@@ -28,7 +28,7 @@ function _spinner_cycle () {
   fi
 }
 export -f _spinner_cycle
-export _spinner_period='0.15s'
+export _SPINNER_PERIOD='0.15s'
 
 # Offer support for environments that don't have access to tput. tput is used to
 # hide and show the cursor.
@@ -64,7 +64,7 @@ function _display_message() {
   if test "${mode}" != 'first'; then
     printf '\e[1A'
   fi
-  printf "\\r%s%$(($(_tput cols)-${#_message}-8))s${status}\\n" "${_message}"
+  printf "\\r%s%$(($(_tput cols)-${#_MESSAGE}-8))s${status}\\n" "${_MESSAGE}"
 }
 export -f _display_message
 
@@ -76,13 +76,13 @@ function _spinner {
       export _s=0
       while true; do
         _display_message 'spinning'
-        sleep ${_spinner_period}
+        sleep ${_SPINNER_PERIOD}
       done
       ;;
 
     stop)
-      test -z "${_spinner_pid+x}" && return 1
-      kill "${_spinner_pid}" > /dev/null 2>&1
+      test -z "${_SPINNER_PID+x}" && return 1
+      kill "${_SPINNER_PID}" > /dev/null 2>&1
       local status
       if (( ${2-0} == 0 )); then
         status="${GREEN}DONE${RESET}"
@@ -93,7 +93,7 @@ function _spinner {
       ;;
 
     *)
-      printf 'ERROR: invalid argument, try {start/stop}' >&2
+      printf 'ERROR: invalid parameter, try {start/stop}' >&2
       exit 2
       ;;
   esac
@@ -102,36 +102,36 @@ export -f _spinner
 
 # Check if spinners are enabled.
 function are-spinners-enabled() {
-  test -z "${SPINNERS_ENABLED+x}" || test "${SPINNERS_ENABLED}" = true
+  test -z "${_SPINNERS_ENABLED+x}" || test "${_SPINNERS_ENABLED}" = true
 }
 export -f are-spinners-enabled
 
 # Check if verbose is enabled.
 function is-verbose-enabled() {
-  test -n "${SPINNERS_VERBOSE+x}" && test "${SPINNERS_VERBOSE}" = true
+  test -n "${_SPINNERS_VERBOSE+x}" && test "${_SPINNERS_VERBOSE}" = true
 }
 export -f is-verbose-enabled
 
 # Start spinner.
 function start-spinner() {
-  if test "${-}" = *x* || test -n "${_spinner_pid+x}" || test ! are-spinners-enabled; then
+  if test "${-}" = *x* || test -n "${_SPINNER_PID+x}" || test ! are-spinners-enabled; then
     return
   fi
-  export _message="${1-}"
+  export _MESSAGE="${1-}"
   _display_message 'first'
   _spinner 'start' &
-  _buffer="$(mktemp)"
-  export _buffer
-  if test -z "${SPINNERS_OUTPUT+x}" || test "${SPINNERS_OUTPUT}" = 'full-output'; then
-    exec 3>&1 1>"${_buffer}" 2>&1
-  elif test "${SPINNERS_OUTPUT}" = 'stdout-only'; then
-    exec 3>&1 1>"${_buffer}" 2>/dev/null
-  elif test "${SPINNERS_OUTPUT}" = 'stderr-only'; then
-    exec 3>&1 1>/dev/null 2>"${_buffer}"
-  elif test "${SPINNERS_OUTPUT}" = 'no-output'; then
+  _BUFFER="$(mktemp)"
+  export _BUFFER
+  if test -z "${_SPINNERS_OUTPUT+x}" || test "${_SPINNERS_OUTPUT}" = 'full-output'; then
+    exec 3>&1 1>"${_BUFFER}" 2>&1
+  elif test "${_SPINNERS_OUTPUT}" = 'stdout-only'; then
+    exec 3>&1 1>"${_BUFFER}" 2>/dev/null
+  elif test "${_SPINNERS_OUTPUT}" = 'stderr-only'; then
+    exec 3>&1 1>/dev/null 2>"${_BUFFER}"
+  elif test "${_SPINNERS_OUTPUT}" = 'no-output'; then
     exec 3>&1 1>/dev/null 2>/dev/null
   fi
-  export _spinner_pid="${!}"
+  export _SPINNER_PID="${!}"
   disown
 }
 export -f start-spinner
@@ -139,23 +139,23 @@ export -f start-spinner
 # Stop spinner.
 function stop-spinner() {
   _tput cvvis
-  if test "${-}" = *x* || test -z "${_spinner_pid+x}" || test ! are-spinners-enabled; then
+  if test "${-}" = *x* || test -z "${_SPINNER_PID+x}" || test ! are-spinners-enabled; then
     return
   fi
   exec 1>&3
   local exit_code="${1-0}"
   _spinner 'stop' "${exit_code}"
-  unset _spinner_pid
+  unset _SPINNER_PID
   if (( exit_code != 0 )) || is-verbose-enabled; then
-    cat "${_buffer}"
+    cat "${_BUFFER}"
   fi
-  rm "${_buffer}"
+  rm "${_BUFFER}"
 }
 export -f stop-spinner
 
 # Disable spinners.
 function disable-spinners() {
-  traps "${the_trap}" --return-code-only
+  traps "${_THE_TRAP}" --return-code-only
   export SPINNERS_ENABLED=false
 }
 export -f disable-spinners
@@ -169,10 +169,10 @@ export -f disable-verbose
 # Configure spinner output to stdout, stderr, both or none.
 function configure-spinner-output() {
   export SPINNERS_OUTPUT=${1-}
-  if test "${SPINNERS_OUTPUT}" != 'full-output' &&
-     test "${SPINNERS_OUTPUT}" != 'stdout-only' &&
-     test "${SPINNERS_OUTPUT}" != 'stderr-only' &&
-     test "${SPINNERS_OUTPUT}" != 'no-output'; then
+  if test "${_SPINNERS_OUTPUT}" != 'full-output' &&
+     test "${_SPINNERS_OUTPUT}" != 'stdout-only' &&
+     test "${_SPINNERS_OUTPUT}" != 'stderr-only' &&
+     test "${_SPINNERS_OUTPUT}" != 'no-output'; then
     printf 'wrong spinner output %s\n' "${mode}" 2>/dev/null
     return 1
   fi
@@ -181,7 +181,7 @@ export -f configure-spinner-output
 
 # Enable spinners.
 function enable-spinners() {
-  traps "${the_trap}"
+  traps "${_THE_TRAP}"
   export SPINNERS_ENABLED=true
 }
 export -f enable-spinners
